# Generated by Django 3.0.4 on 2020-06-22 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('type', models.CharField(choices=[('b', 'Boy'), ('g', 'Girl'), ('f', 'family')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Egde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='geny.Node')),
                ('tar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='geny.Node')),
            ],
        ),
    ]
