# Generated by Django 3.0.4 on 2020-06-22 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geny', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Egde',
            new_name='Edge',
        ),
    ]
